//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laba3
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAMES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GAMES()
        {
            this.CHARACTERS = new HashSet<CHARACTERS>();
        }
    
        public int GAMEID { get; set; }
        public string TITLE { get; set; }
        public Nullable<System.DateTime> REALESEDATE { get; set; }
        public string PLATFORMS { get; set; }
        public Nullable<decimal> RATING { get; set; }
        public string DESCRIPTIONn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHARACTERS> CHARACTERS { get; set; }
    }
}
